#index:
#    path: /
#    controller: App\Controller\DefaultController::index

before:
    path: /{_locale}
    controller: App\Controller\HomeController::viewHome
    defaults:   {_locale: fr}
    requirements:
        _locale: en|fr

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }
